const AUTH_STORAGE_KEY='emirAdminAuth.v1';
const SUPABASE_SESSION_KEY='emirSupabaseSession.v1';
const AUTH_USER='admin';
const SUPABASE_ADMIN_EMAIL='respongo@gmail.com';
const AUTH_PASSWORD_HASH='57083316973eacaac054ea9dc129260c46498af7d2b96d30cc964541987a5dd9';
const loginScreen=document.querySelector('#admin-login');
const adminApp=document.querySelector('.admin-app');
const loginError=document.querySelector('#login-error');
function sessionGet(key){try{return window.sessionStorage?.getItem(key)}catch(e){return null}}
function sessionSet(key,value){try{window.sessionStorage?.setItem(key,value)}catch(e){}}
function sessionRemove(key){try{window.sessionStorage?.removeItem(key)}catch(e){}}
async function passwordHash(value){if(!window.crypto?.subtle)return '';const bytes=new TextEncoder().encode(value);const digest=await window.crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,'0')).join('')}
function setAuthenticated(authenticated){loginScreen.hidden=authenticated;adminApp.hidden=!authenticated;if(authenticated){loginError.hidden=true;document.body.classList.add('admin-authenticated')}else{document.body.classList.remove('admin-authenticated');document.querySelector('#login-form input[name="password"]').value='';document.querySelector('#login-form input[name="username"]').focus()}}
function runtimeConfig(){const config=window.__SUPABASE_CONFIG__||{};return {url:String(config.url||'').replace(/\/$/,''),key:String(config.publishableKey||config.anonKey||'')}}
function configuredSupabase(){const runtime=runtimeConfig();const saved=typeof state==='object'&&state?.site?{url:String(state.site.supabaseUrl||'').replace(/\/$/,''),key:String(state.site.supabaseAnonKey||'')}:{url:'',key:''};return {url:saved.url||runtime.url,key:saved.key||runtime.key}}
async function supabaseSignIn(email,password){const config=configuredSupabase();if(!config.url||!config.key)throw new Error('Supabase ayarları eksik');const response=await fetch(`${config.url}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:config.key,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await response.json().catch(()=>({}));if(!response.ok||!data.access_token)throw new Error(data.error_description||data.msg||'Supabase girişi başarısız');return data}
async function handleLogin(event){event.preventDefault();const form=event.currentTarget;const username=form.elements.username.value.trim();const password=form.elements.password.value;let valid=false;const config=configuredSupabase();if(config.url&&config.key){try{const email=username.includes('@')?username:SUPABASE_ADMIN_EMAIL;const session=await supabaseSignIn(email,password);sessionSet(SUPABASE_SESSION_KEY,session.access_token);valid=true}catch(error){console.warn('Supabase girişi başarısız',error)}}else{valid=username===AUTH_USER&&(await passwordHash(password))===AUTH_PASSWORD_HASH}if(!valid){loginError.hidden=false;form.elements.password.value='';form.elements.password.focus();return}sessionSet(AUTH_STORAGE_KEY,'1');setAuthenticated(true)}
function logout(){sessionRemove(AUTH_STORAGE_KEY);sessionRemove(SUPABASE_SESSION_KEY);setAuthenticated(false)}
document.querySelector('#login-form').addEventListener('submit',handleLogin);
document.querySelector('#logout-button').addEventListener('click',logout);
setAuthenticated(sessionGet(AUTH_STORAGE_KEY)==='1');

const STORAGE_KEY='emirPortfolioData.v1';
const DEFAULT_SITE={heroKicker:'YÖNETMEN & FİLM YAPIMCISI',location:'İSTANBUL, TR',tagline:'Moda, reklam\nve hareketli görüntü.',aboutLabel:'KAMERA ARKASINDA',aboutName:'Emir Selahattin\nŞahin.',aboutLead:'Moda, reklam ve dijital içerik alanlarında çalışan bağımsız yönetmen ve film yapımcısı.',aboutP1:'Kadir Has Üniversitesi Sinema ve Televizyon Bölümü’nde eğitim aldı. Kariyerine Tolan Film’de başladı; kamera, prodüksiyon ve backstage çalışmalarının ardından kısa film projelerinde görüntü yönetmenliği yaptı.',aboutP2:'No. Studio ile Mavi, DESA ve Communite gibi markaların projelerinde kamera operatörlüğü, yardımcı yönetmenlik ve kurgu görevleri üstlendi. İlk moda filmi yönetmenliğini DESA’nın #KendiniYaşa kampanyasında gerçekleştirdi.',practice:['Yönetmenlik','Kamera','Kurgu & renk'],caption:'Beşiktaş, İstanbul',contactKicker:'YENİ PROJELER İÇİN',contactTitle:'Birlikte çalışalım.',email:'sahinemir@outlook.com',phone:'+90 542 417 18 14',instagram:'https://www.instagram.com/emir.mov/',supabaseUrl:'',supabaseAnonKey:''};
const original=Array.isArray(window.projects)?window.projects:[];
const memoryFallback={};
const mediaStore=window.mediaStore;
const htmlEntities={'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'};
function esc(value){return String(value??'').replace(/[&<>"']/g,character=>htmlEntities[character])}
function storageGet(key){try{if(window.localStorage)return window.localStorage.getItem(key)}catch(e){}return memoryFallback[key]||null}
function storageSet(key,value){try{if(window.localStorage){window.localStorage.setItem(key,value);return}}catch(e){}memoryFallback[key]=value}
function load(){try{const x=JSON.parse(storageGet(STORAGE_KEY)||'null');const site={...DEFAULT_SITE,...(x?.site||{})};Object.keys(DEFAULT_SITE).forEach(key=>{if(site[key]===''&&DEFAULT_SITE[key])site[key]=DEFAULT_SITE[key]});return {site,projects:Array.isArray(x?.projects)?x.projects:original.map(item=>({...item}))}}catch(e){return {site:{...DEFAULT_SITE},projects:original.map(item=>({...item}))}}}
let state=load();
let pendingDelete=null;
let editorFileRefs=[];
let pendingVideoFiles=[];
let pendingCoverFile=null;
let removedMediaRefs=new Set();
let coverPreviewUrl=null;

function isMediaRef(value){return mediaStore?.isRef?.(value)===true}
function mediaPath(value){if(!value)return 'assets/poster-5.jpg';return value.startsWith('assets/')||value.startsWith('videos/')||/^https?:\/\//i.test(value)?value:'assets/'+value}
function collectMedia(project){return [project?.cover,...(project?.files||[])].filter(isMediaRef)}
async function cleanupMedia(refs){const used=new Set(state.projects.flatMap(project=>collectMedia(project)));for(const ref of refs){if(!used.has(ref)){try{await mediaStore?.remove?.(ref)}catch(e){console.warn('Medya temizlenemedi',e)}}}}
function setImageSource(img,ref){img.src=mediaPath(ref);if(isMediaRef(ref)){mediaStore.resolve(ref).then(result=>{if(result)img.src=result.url}).catch(()=>{})}}
function formatBytes(bytes){if(!Number.isFinite(bytes))return '';if(bytes<1024*1024)return Math.max(1,Math.round(bytes/1024))+' KB';return (bytes/(1024*1024)).toFixed(1)+' MB'}
function persist(message='Kaydedildi'){storageSet(STORAGE_KEY,JSON.stringify(state));const node=document.querySelector('#save-state');node.textContent=message;node.classList.remove('unsaved');toast(message)}
function toast(message){const n=document.querySelector('#toast');n.textContent=message;n.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>n.classList.remove('show'),2600)}
function renderOverview(){const projects=state.projects;document.querySelector('#stat-projects').textContent=projects.length;document.querySelector('#stat-films').textContent=projects.reduce((n,p)=>n+(p.files?.length||0),0);document.querySelector('#stat-featured').textContent=projects.filter(p=>p.featured).length;document.querySelector('#nav-count').textContent=projects.length;const recent=document.querySelector('#recent-projects');recent.replaceChildren();projects.slice(0,5).forEach(p=>{const row=document.createElement('div');row.className='recent-row';row.innerHTML='<img class="recent-thumb" alt=""><div><strong>'+esc(p.brand)+'</strong><small>'+esc(p.title)+'</small></div><span>'+(p.files?.length||0)+' film</span>';recent.append(row);setImageSource(row.querySelector('img'),p.cover)})}
function renderProjects(){const list=document.querySelector('#project-list');const query=(document.querySelector('#project-search').value||'').toLowerCase().trim();const filtered=state.projects.filter(p=>`${p.brand} ${p.title} ${p.role}`.toLowerCase().includes(query));document.querySelector('#project-result-count').textContent=`${filtered.length} proje`;list.replaceChildren();if(!filtered.length){list.innerHTML='<div class="empty-row">Aramanla eşleşen bir proje yok.</div>';return}filtered.forEach(p=>{const row=document.createElement('article');row.className='project-admin-row';row.innerHTML='<img alt=""><div><strong>'+esc(p.brand)+'</strong><small>'+esc(p.title)+'</small></div><div class="role-cell">'+esc(p.role||'Görev eklenmemiş')+'</div><div><small>'+(p.files?.length||0)+' film'+(p.featured?' · Öne çıkan':'')+'</small></div><div class="project-actions"><button data-edit="'+esc(p.id)+'">Düzenle</button><button class="delete" data-delete="'+esc(p.id)+'">Sil</button></div>';list.append(row);setImageSource(row.querySelector('img'),p.cover)});list.querySelectorAll('[data-edit]').forEach(button=>button.onclick=()=>openEditor(button.dataset.edit));list.querySelectorAll('[data-delete]').forEach(button=>button.onclick=()=>askDelete(button.dataset.delete))}
function fillForm(form,data){Object.entries(data).forEach(([key,value])=>{const field=form.querySelector(`[name="${key}"]`);if(!field)return;if(field.type==='checkbox')field.checked=Boolean(value);else field.value=Array.isArray(value)?value.join(', '):(value??'')})}
function siteFrom(form){const out={...state.site};Array.from(form.elements).forEach(field=>{if(!field.name)return;out[field.name]=field.name==='practice'?field.value.split(',').map(x=>x.trim()).filter(Boolean):field.type==='checkbox'?field.checked:field.value.trim()});return out}

function clearCoverPreview(){if(coverPreviewUrl){URL.revokeObjectURL(coverPreviewUrl);coverPreviewUrl=null}}
function renderCoverPreview(ref){const preview=document.querySelector('#cover-preview');const image=preview.querySelector('img');clearCoverPreview();const value=ref||'assets/poster-5.jpg';image.src=mediaPath(value);preview.hidden=false;if(isMediaRef(value)){mediaStore.resolve(value).then(result=>{if(result)image.src=result.url}).catch(()=>{})}}
function renderCoverFile(file){const preview=document.querySelector('#cover-preview');const image=preview.querySelector('img');clearCoverPreview();if(!file){renderCoverPreview('');return}coverPreviewUrl=URL.createObjectURL(file);image.src=coverPreviewUrl;preview.hidden=false}
function renderVideoList(){const list=document.querySelector('#video-list');list.replaceChildren();if(!editorFileRefs.length&&!pendingVideoFiles.length){list.innerHTML='<p class="media-empty">Henüz video eklenmedi. Birden fazla dosyayı aynı anda seçebilirsin.</p>';return}editorFileRefs.forEach((ref,index)=>{const row=document.createElement('div');row.className='media-row';row.innerHTML='<span class="media-index">'+String(index+1).padStart(2,'0')+'</span><div class="media-info"><strong>'+esc(isMediaRef(ref)?(mediaStore.label(ref)||'İçe aktarılan dosya'):(String(ref).split('/').pop()||ref))+'</strong><small>'+esc(isMediaRef(ref)?'Tarayıcıya kaydedildi':'Bağlantı / site dosyası')+'</small></div><button type="button" class="media-remove" aria-label="Videoyu çıkar">×</button>';row.querySelector('button').onclick=()=>{if(isMediaRef(ref))removedMediaRefs.add(ref);editorFileRefs.splice(index,1);document.querySelector('#project-form [name="files"]').value=editorFileRefs.join('\n');renderVideoList()};list.append(row);if(isMediaRef(ref))mediaStore.get(ref).then(entry=>{const strong=row.querySelector('strong');if(entry&&strong)strong.textContent=entry.name}).catch(()=>{})});pendingVideoFiles.forEach((file,index)=>{const row=document.createElement('div');row.className='media-row pending';row.innerHTML='<span class="media-index">＋</span><div class="media-info"><strong>'+esc(file.name)+'</strong><small>Yeni dosya · '+formatBytes(file.size)+'</small></div><button type="button" class="media-remove" aria-label="Yeni videoyu çıkar">×</button>';row.querySelector('button').onclick=()=>{pendingVideoFiles.splice(index,1);renderVideoList()};list.append(row)})}
function syncFilesField(){const field=document.querySelector('#project-form [name="files"]');editorFileRefs=field.value.split(/\r?\n/).map(value=>value.trim()).filter(Boolean);renderVideoList()}
function resetEditorMedia(){pendingVideoFiles=[];pendingCoverFile=null;removedMediaRefs=new Set();clearCoverPreview();const coverFile=document.querySelector('#cover-file');const videoFiles=document.querySelector('#video-files');if(coverFile)coverFile.value='';if(videoFiles)videoFiles.value=''}
function openEditor(id){const form=document.querySelector('#project-form');const project=id?state.projects.find(item=>item.id===id):{id:'',brand:'',title:'',role:'',cover:'assets/poster-5.jpg',files:[],featured:false};if(!project)return;resetEditorMedia();document.querySelector('#dialog-title').textContent=id?'Portföyü düzenle':'Yeni portföy';form.reset();fillForm(form,{...project,files:(project.files||[]).join('\n')});editorFileRefs=[...(project.files||[])];renderVideoList();renderCoverPreview(project.cover||'assets/poster-5.jpg');document.querySelector('#project-dialog').showModal()}
async function saveProject(form){const saveButton=form.querySelector('button[type="submit"]');const oldProject=state.projects.find(item=>item.id===form.elements.id.value);const created=[];saveButton.disabled=true;saveButton.textContent='Dosyalar kaydediliyor…';try{let cover=form.elements.cover.value.trim()||'assets/poster-5.jpg';if(pendingCoverFile){const id=await mediaStore.put(pendingCoverFile);cover='upload:'+id;created.push(cover)}const imported=[];for(const file of pendingVideoFiles){const id=await mediaStore.put(file);const ref='upload:'+id;created.push(ref);imported.push(ref)}const data={id:form.elements.id.value||`project-${Date.now()}`,brand:form.elements.brand.value.trim(),title:form.elements.title.value.trim(),role:form.elements.role.value.trim(),cover,files:[...editorFileRefs,...imported],featured:form.elements.featured.checked};const oldIndex=state.projects.findIndex(item=>item.id===data.id);if(oldIndex>-1)state.projects[oldIndex]=data;else state.projects.unshift(data);if(data.featured)state.projects.forEach(item=>{if(item.id!==data.id)item.featured=false});persist(oldIndex>-1?'Portföy güncellendi':'Portföy oluşturuldu');document.querySelector('#project-dialog').close();renderAll();await cleanupMedia([...collectMedia(oldProject),...removedMediaRefs])}catch(error){for(const ref of created)await mediaStore.remove(ref).catch(()=>{});console.error(error);toast('Dosyalar kaydedilemedi. Tarayıcı depolama alanını kontrol et.')}finally{saveButton.disabled=false;saveButton.textContent='Portföyü kaydet'}}
function askDelete(id){pendingDelete=id;document.querySelector('#confirm-dialog').hidden=false}
async function deleteProject(){if(!pendingDelete)return;const target=state.projects.find(item=>item.id===pendingDelete);state.projects=state.projects.filter(item=>item.id!==pendingDelete);pendingDelete=null;document.querySelector('#confirm-dialog').hidden=true;persist('Portföy silindi');renderAll();await cleanupMedia(collectMedia(target))}
function renderAll(){renderOverview();renderProjects()}
function switchView(name){document.querySelectorAll('.view').forEach(view=>view.classList.toggle('active-view',view.id===`view-${name}`));document.querySelectorAll('.nav-item').forEach(view=>view.classList.toggle('active',view.dataset.view===name));const titles={overview:['ÇALIŞMA ALANI','Genel bakış'],projects:['İÇERİK YÖNETİMİ','Portföyler'],content:['SAYFA İÇERİĞİ','Hakkında'],settings:['GENEL YAPILANDIRMA','Site ayarları']};document.querySelector('#view-kicker').textContent=titles[name][0];document.querySelector('#view-title').textContent=titles[name][1];document.querySelector('.sidebar').classList.remove('open');if(name==='content')fillForm(document.querySelector('#about-form'),state.site);if(name==='settings'){const values={...state.site};const config=runtimeConfig();if(!values.supabaseUrl)values.supabaseUrl=config.url;if(!values.supabaseAnonKey)values.supabaseAnonKey=config.key;fillForm(document.querySelector('#settings-form'),values)}}
function safeFileName(name){return String(name||'media').normalize('NFKD').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,100)||'media'}
async function uploadMediaRef(ref,config,token){if(!isMediaRef(ref))return ref;const entry=await mediaStore.get(ref);if(!entry?.blob)throw new Error(`Medya bulunamadı: ${ref}`);const path=`uploads/${entry.id}-${safeFileName(entry.name)}`;const response=await fetch(`${config.url}/storage/v1/object/portfolio-media/${encodeURIComponent(path).replace(/%2F/g,'/')}`,{method:'POST',headers:{apikey:config.key,Authorization:`Bearer ${token}`,'Content-Type':entry.type||'application/octet-stream','x-upsert':'true'},body:entry.blob});if(!response.ok)throw new Error(await response.text());return `${config.url}/storage/v1/object/public/portfolio-media/${path.split('/').map(encodeURIComponent).join('/')}`}
async function remotePayload(config,token){const payload={site:{...state.site},projects:[]};delete payload.site.supabaseUrl;delete payload.site.supabaseAnonKey;for(const project of state.projects){const copy={...project};copy.cover=await uploadMediaRef(copy.cover,config,token);copy.files=[];for(const file of project.files||[])copy.files.push(await uploadMediaRef(file,config,token));payload.projects.push(copy)}return payload}
async function syncSupabase(){const config=configuredSupabase();const token=sessionGet(SUPABASE_SESSION_KEY);if(!config.url||!config.key){toast('Önce Supabase URL ve Publishable/anon key gir');switchView('settings');return}if(!token){toast('Supabase oturumu bulunamadı · çıkış yapıp tekrar giriş yap');return}const button=document.querySelector('#sync-supabase');button.disabled=true;button.textContent='Dosyalar yükleniyor...';try{const payload=await remotePayload(config,token);button.textContent='Senkronize ediliyor...';const response=await fetch(`${config.url}/rest/v1/site_content?on_conflict=id`,{method:'POST',headers:{apikey:config.key,Authorization:`Bearer ${token}`,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates'},body:JSON.stringify({id:'main',payload,updated_at:new Date().toISOString()})});if(!response.ok)throw new Error(await response.text());const badge=document.querySelector('.integration-state');if(badge){badge.textContent='Bağlı';badge.classList.remove('pending')}toast('Supabase senkronizasyonu tamamlandı')}catch(error){console.error(error);toast('Supabase bağlantısı kurulamadı · ayarları ve Storage politikalarını kontrol et')}finally{button.disabled=false;button.textContent='Supabase’a senkronize et ↗'}}

document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view)));
document.querySelectorAll('[data-action="new"]').forEach(button=>button.addEventListener('click',()=>openEditor()));
document.querySelector('#project-search').addEventListener('input',renderProjects);
document.querySelector('#project-form').addEventListener('submit',event=>{event.preventDefault();saveProject(event.currentTarget)});
document.querySelector('#project-form [name="files"]').addEventListener('input',syncFilesField);
document.querySelector('#cover-file').addEventListener('change',event=>{pendingCoverFile=event.target.files?.[0]||null;if(pendingCoverFile){document.querySelector('#project-form [name="cover"]').value='';renderCoverFile(pendingCoverFile);}});
document.querySelector('#project-form [name="cover"]').addEventListener('input',event=>{if(pendingCoverFile&&event.target.value.trim()){pendingCoverFile=null;document.querySelector('#cover-file').value=''}renderCoverPreview(event.target.value.trim())});
document.querySelector('#remove-cover').addEventListener('click',()=>{const current=document.querySelector('#project-form [name="cover"]').value.trim();if(isMediaRef(current))removedMediaRefs.add(current);pendingCoverFile=null;document.querySelector('#cover-file').value='';document.querySelector('#project-form [name="cover"]').value='assets/poster-5.jpg';renderCoverPreview('assets/poster-5.jpg')});
document.querySelector('#video-files').addEventListener('change',event=>{const incoming=Array.from(event.target.files||[]);const known=new Set(pendingVideoFiles.map(file=>`${file.name}:${file.size}:${file.lastModified}`));pendingVideoFiles=[...pendingVideoFiles,...incoming.filter(file=>{const key=`${file.name}:${file.size}:${file.lastModified}`;if(known.has(key))return false;known.add(key);return true})];event.target.value='';renderVideoList()});
document.querySelector('#close-dialog').onclick=()=>document.querySelector('#project-dialog').close();
document.querySelector('#cancel-dialog').onclick=()=>document.querySelector('#project-dialog').close();
document.querySelector('#project-dialog').addEventListener('close',()=>{clearCoverPreview();pendingVideoFiles=[];pendingCoverFile=null;removedMediaRefs=new Set()});
document.querySelector('#confirm-delete').onclick=deleteProject;
document.querySelector('#cancel-delete').onclick=()=>{pendingDelete=null;document.querySelector('#confirm-dialog').hidden=true};
document.querySelector('#about-form').addEventListener('submit',event=>{event.preventDefault();state.site=siteFrom(event.currentTarget);persist('Hakkında kaydedildi')});
document.querySelector('#settings-form').addEventListener('submit',event=>{event.preventDefault();state.site=siteFrom(event.currentTarget);persist('Ayarlar kaydedildi')});
document.querySelector('#sync-supabase').onclick=syncSupabase;
document.querySelector('#menu-toggle').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
renderAll();
